# Numpy Tutorial

Numpy provides support for large, multi-dimensional arrays and matrices as well as mathematical functions to operate on these arrays

Documentation: https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

In [22]:
#create and print arrays 

a = np.arange(6)                         # 1d array
print(a, ' a\n\n') 

b = np.arange(12).reshape(4,3)           # 2d array
print(b, ' b\n\n') 
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c, ' c\n')

[0 1 2 3 4 5]  a


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]  b


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]  c



In [23]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a, 'a\n')              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b, 'b\n')              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c, 'c\n')               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d, 'd\n')              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e, 'e\n')                     # Might print "[[ 0.91940167  0.08143941]
               

[[0. 0.]
 [0. 0.]] a

[[1. 1.]] b

[[7 7]
 [7 7]] c

[[1. 0.]
 [0. 1.]] d

[[0.1399758  0.26190786]
 [0.87739624 0.181359  ]] e



### Slicing

See: 

In [24]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b, 'b\n')

# Use slicing to pull out the subarray consisting of the last 2 columns from all rows
# b is the following array of shape (3, 2):
# [[2 3]
#  [6 7]]
c = a[:, -2:]
print(c, 'c\n')

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[1, 1] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[1, 2])   # Prints "77"
print(c[1, 0])   # Prints "77"

[[2 3]
 [6 7]] b

[[ 3  4]
 [ 7  8]
 [11 12]] c

2
77
77


In [27]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape, '\n')  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape, '\n')  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"
#Reshape 
col1_r1 = col_r1.reshape(3)
print(col_r1, col_r1.shape)
col_r1 = col_r1.reshape(3, 1)
print(col_r1, col_r1.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4) 

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1) 

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Numpy Array Math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

#https://cs231n.github.io/python-numpy-tutorial/

#### Inner Products

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [6]:
#source: https://cs231n.github.io/python-numpy-tutorial/

import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

print(' ----------')

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"



print(' ----------')

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)


10
[4 6]
[3 7]
 ----------
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
 ----------
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Concatenating and Reshaping Numpy Arrays

In [29]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

vertical_stack = np.vstack((a,b))
print(vertical_stack, '  vertical_stack')

[[1 2 3]
 [2 3 4]]   vertical_stack


In [30]:
horizontal_stack = np.hstack((a,b))
print(horizontal_stack, '  horizontal_stack')

[1 2 3 2 3 4]   horizontal_stack


In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
ab = np.concatenate((a, b), axis=0)
print(ab, '  concatenate  axis=0')

ab = np.concatenate((a, b.T), axis=1)  # note b.T is same is b.transpose()
print(ab, '  concatenate  axis=1')

ab = np.concatenate((a, b), axis=None)
print(ab, '  concatenate  axis= none')

[[1 2]
 [3 4]
 [5 6]]   concatenate  axis=0
[[1 2 5]
 [3 4 6]]   concatenate  axis=1
[1 2 3 4 5 6]   concatenate  axis= none


In [32]:
x = np.arange(9.0)
x_split = np.split(x, 3)

print(x, '  original x')

print(x_split, '  x split into three')

[0. 1. 2. 3. 4. 5. 6. 7. 8.]   original x
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]   x split into three


In [5]:
z = np.arange(6) # produces and array of 0 - 5
print(z, '  original z')

z_reshape = z.reshape((3, 2))
print(z_reshape, '  reshaped z')

z_flat = np.reshape(z_reshape, 6)
print(z_flat, '  flatten z\n')

#if we know what one axis should be reshaped to, but we don't know how this will affect another 
# axis, then you can use -1 and numpy will figure it out for us
z_idk = z.reshape((3,-1))
print(z_idk)
print(z_idk.shape)
print("\n")
z_idk = z_idk.reshape(-1,6)
print(z_idk)
print(z_idk.shape)

[0 1 2 3 4 5]   original z
[[0 1]
 [2 3]
 [4 5]]   reshaped z
[0 1 2 3 4 5]   flatten z

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


[[0 1 2 3 4 5]]
(1, 6)


In [35]:
z_flat= z_reshape.flatten()
print(z_flat, '  another way to flatten z')

[0 1 2 3 4 5]   another way to flatten z


### Saving and Loading Numpy Arrays

In [40]:
b = np.random.rand(10,10)

for x in range(1, b.shape[0]):
    for y in range(1, b.shape[1], 2):
        b[x][y] = y*x 

double_mat =   b * 2
print(double_mat.shape)

np.savetxt('mynumpy.txt', double_mat, delimiter = ' ',  fmt='%1.2f' )
np.savetxt('mynumpy.csv', double_mat, delimiter = ',',  fmt='%1.2f' )
np.savetxt('mynumpy_fmt.csv', double_mat, delimiter = ',',  fmt='%1.5f' )

(10, 10)


In [48]:
data_load = np.loadtxt('mynumpy.txt')
print(data_load.shape)
print(data_load[0])

data_load_csv = np.loadtxt('mynumpy.csv', delimiter = ',')
print(data_load_csv.shape)
print(data_load_csv[0])

data_load_fmt = np.loadtxt('mynumpy_fmt.csv', delimiter = ',')
print(data_load_fmt.shape)
print(data_load_fmt[0])

(10, 10)
[1.53 1.95 1.53 1.16 0.51 0.34 1.3  0.97 0.25 1.59]
(10, 10)
[1.53 1.95 1.53 1.16 0.51 0.34 1.3  0.97 0.25 1.59]
(10, 10)
[1.53206 1.94686 1.53043 1.16296 0.50824 0.3371  1.29506 0.96976 0.24857
 1.59499]
